version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: datatracker-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: datatracker-backend
    build: ./backend
    environment:
      PRODUCTION: "True"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env

  frontend:
    container_name: datatracker-frontend
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
