### Create a new entry for a dataset
POST http://localhost:8080/datasets/2/entries
Content-Type: application/json

{
  "value": 100.5,
  "label": "1 Sales",
  "date": "2025-01-01T00:00:00Z"
}

###

### Create a new entry for a dataset
POST http://localhost:8080/datasets/2/entries
Content-Type: application/json

{
  "value": 104.5,
  "label": "2 Sales",
  "date": "2025-02-01T00:00:00Z"
}

###

### Create a new entry for a dataset
POST http://localhost:8080/datasets/2/entries
Content-Type: application/json

{
  "value": 90.5,
  "label": "3 Sales",
  "date": "2025-03-01T00:00:00Z"
}

###

### List all entries for a dataset
GET http://localhost:8080/datasets/2/entries
Accept: application/json

###

### Update an entry by ID
PUT http://localhost:8080/entries/2
Content-Type: application/json

{
  "datasetId": 1,
  "value": 105.0,
  "label": "Updated January Sales",
  "date": "2025-01-01T00:00:00Z"
}

###

### Delete an entry by ID
DELETE http://localhost:8080/entries/2
